insert into podcasts values (select nextval('podcast_id_seq'), current_date, current_date, "The Daily", 0, image, intro, cid, 1)
insert into podcasts values (select nextval('podcast_id_seq'), current_date, current_date, "Conan O'Brien Needs A Friend", 0, image, intro, cid, 1)
insert into podcasts values (select nextval('podcast_id_seq'), current_date, current_date, "SmartLess", 0, image, intro, cid, 1)
insert into podcasts values (select nextval('podcast_id_seq'), current_date, current_date, "How I Built This with Guy Raz", 0, image, intro, cid, 1)
insert into podcasts values (select nextval('podcast_id_seq'), current_date, current_date, "7 Good Minutes Daily Self-Improvement", 0, image, intro, cid, 1)

title: "The Daily", category: "News", rating: 0,0
title: "Conan O'Brien Needs A Friend", category: "Comedy", rating: 0.0
title: "SmartLess", category: "Education", rating: 0.0
title: "How I Built This with Guy Raz", category: "Business", rating: 0.0
title: "7 Good Minutes Daily Self-Improvement", category: "Health & Fitness", rating: 0.0

title: `The Sunday Read: 'Rembrandt in the Blood'`
,content: `It was in the winter of 2016 that Jan Six, a Dutch art dealer based in Amsterdam, made a discovery that would upend his life. He was leafing through a Christie’s catalog when he spotted a painting featuring a young man wearing a dazed look, a lace collar and a proto-Led Zeppelin coif. Christie’s had labeled it a painting by one of Rembrandt’s followers, but Mr. Six knew it was by the Dutch master himself.
Today on The Sunday Read, a look at Mr. Six’s discovery of the first new Rembrandt painting in over four decades, and the fallout from finding it.
_This story was written by Russell Shorto and recorded by Audm. To hear more audio stories from publishers like The New York Times, __download Audm for iPhone or Android__._`

title: `A Nursing Home’s First Day Out of Lockdown`
,content: `The Good Shepherd Nursing Home in West Virginia lifted its coronavirus lockdown in February.
For months, residents had been confined to their rooms, unable to mix. But with everybody now vaccinated, it was finally time to see one another again.
We share some of the relief and joy about the tip-toe back to normalcy for staff members and residents.
Guest: Sarah Mervosh, a national reporter for The New York Times.
Sign up here to get The Daily in your inbox each morning. And for an exclusive look at how the biggest stories on our show come together, subscribe to our newsletter.
Background reading:
* The Good Shepherd Nursing Home, where vaccinations have finished, offers a glimpse at what the other side of the pandemic might look like.
* Nursing homes, once hot spots of the coronavirus, are far outpacing the rest of the United States in Covid declines.
For more information on today’s episode, visit nytimes.com/thedaily.
Transcripts of each episode will be made available by the next workday.`

title: `The State of Vaccinations`
,content: `The United States has never undertaken a vaccination campaign of the scale and speed of the Covid-19 program. Despite a few glitches, the country appears to be on track to offer shots to all adults who want one by May 1.
We look at the ups and downs in the American vaccination campaign and describe what life after inoculation might look like.
Guest: Apoorva Mandavilli, a science and global health reporter for The New York Times.
Sign up here to get The Daily in your inbox each morning. And for an exclusive look at how the biggest stories on our show come together, subscribe to our newsletter.
Background reading:
* It’s not clear how easily vaccinated people may spread the virus, but the answer to that question is coming soon. Until then, scientists urge caution.
* Many scientists are expecting another rise in infections. But this time, vaccinations should help to counter the surge. By summer, Americans may be looking at a return to normal life.
For more information on today’s episode, visit nytimes.com/thedaily.
Transcripts of each episode will be made available by the next workday.`


createEpisode(input:{podcastId: 2, title: "Stephen Colbert", content: "This week we take a wild ride through the brain of Mr. Stephen Colbert (host, comedian, pro skier). The gang examines Jason's 'pleasant hostility,' Stephen's Lord of the Rings memorabilia, and a few '100% true' stories."}) {ok}
createEpisode(input:{podcastId: 2, title: "W. Kamau Bell", content: "We are joined this week by Mr. W. Kamau Bell, television host and stand-up comic, and wicked smart dude. He tells us about the birds and the bees, when to teach your children new things, and his grand ideas for Ozark's next season."}) {ok}
createEpisode(input:{podcastId: 2, title: "Brad Paisley", content: "The incredibly talented Brad Paisley shares his perfect blend of country and comedy while we all blush with a crush. ""I'm takin' my baby out into this cornfield tonight""... is exactly how we felt after the interview too."}) {ok}


title: "Seth Meyers",
content: "Comedian and television host Seth Meyers feels anxious and excited about being Conan O’Brien’s friend.
Seth sits down with Conan to talk about coming on to SNL as a cast member first and a writer second, parsing praise from the enigmatic Lorne Michaels, and lessons learned at the Late Night desk. Later, Conan takes it up a notch in his quest for the perfect pen.
Got a question for Conan? Call our voicemail: (323) 451-2821.
For Conan videos, tour dates and more visit TeamCoco.com."

title: "Kate Hudson",
content: "Actress and entrepreneur Kate Hudson feels insecure about being Conan O’Brien’s friend.
Kate sits down with Conan to talk about the key to being a good salesperson, rediscovering the music of the 90s through her kids, and family lessons learned from iconic parents Goldie Hawn and Kurt Russell. Plus, Conan shares an urgent news update with his team.
Got a question for Conan? Call our voicemail: (323) 451-2821.
For Conan videos, tour dates and more visit TeamCoco.com."

title: "Shaquille O'Neal",
content: "Basketball legend Shaquille O’Neal feels enigmatic about being Conan O’Brien’s friend. Shaq sits down with Conan to talk about his uniquely philosophical outlook, being yelled at by Charles Barkley’s mother, how he decides which brands to rep, and remembering Kobe. Later, Conan reprimands his assistant Sona over a mistaken order of pens. Got a question for Conan? Call our voicemail: (323) 451-2821. For Conan videos, tour dates and more visit TeamCoco.com."



title: "Achieve Your Goals By Never Giving Up On Your Dreams",
content: "In this episode, we have an inspiring message about Never Giving Up On Your Dreams. Go to https://7goodminutes.com/1179 for full show notes. Don't forget to subscribe, rate, and share it with a friend or two!"

title: "Do The Hard Things First",
content: "In this episode, we learn why it's important that you Do The Hard Things First. Go to https://7goodminutes.com/1178 for full show notes. Don't forget to subscribe, rate, and share it with a friend or two!"


title: "How To Develop Mental Toughness",
content: "In this episode, in our Freddy Fri Day segment, we learn How To Develop Mental Toughness. Go to https://7goodminutes.com/1177 for full show notes. Don't forget to subscribe, rate, and share it with a friend or two!"



title: "UPPAbaby: Bob and Lauren Monahan",
content: "As a product developer, Bob Monahan worked with some iconic brands: the Pump at Reebok, the Taurus and Mustang at Ford. When he moved on to work at a baby products company, he happened to discover another set of wheels that caught his eye: a sleek-looking stroller that could accommodate a car-seat or a bassinet. Bob was itching to start his own venture, so in 2006, with the help of his wife Lauren, he launched UPPAbaby and started selling a European-style stroller at an 'entry-level luxury' price. As a dad himself, Bob guessed that other dads would be intrigued by UPPAbaby's design; meanwhile, big-name celebrities started to use the stroller, and photos of them pushing it helped accelerate sales. The brand grew quickly, and 15 years after its launch, UPPAbaby employs over 100 people and sells strollers in more than 50 countries. How I Built This Summit - information and tickets at: http://summit.npr.org"

title: "How I Built Resilience: Vivian Ku, Restaurateur"
content: "Vivian Ku is a Taiwanese-American restaurateur who owns three different Taiwanese restaurants in Los Angeles. After the pandemic halted her plans for expansion, Vivian decided to close her two restaurants until May and pivoted her expansion plans into a breakfast pop-up. Vivian talks to Guy about why she decided to serve Taiwanese food and the pros and cons of opening a restaurant during a pandemic. These conversations are excerpts from our How I Built Resilience series, where Guy talks online with founders and entrepreneurs about how they're navigating turbulent times."

title: "Hinge: Justin McLeod",
content: ,"In 2010, Justin McLeod was in business school, still trying to get over a bad breakup that had happened years before. Determined to solve his own problem and convinced that the best way to meet people was through friends of friends, he built an app to replicate that experience. Gradually, Hinge grew into a streamlined swiping platform that yielded mixed results: good dates, bad hookups, mismatched swipes, and missed opportunities. Disappointed with this outcome and inspired by a sudden twist in his own love life, Justin redesigned Hinge as an app for finding meaningful relationships, with the tag line 'designed to be deleted.' Today, Hinge is owned by Match Group and is one of the most popular dating apps in the U.S. How I Built This Summit - information and tickets at: http://summit.npr.org"



insert into category values ((select nextval('category_id_seq')), current_date, current_date, 'News', null, 'news');
insert into category values ((select nextval('category_id_seq')), current_date, current_date, 'Education', null, 'education');
insert into category values ((select nextval('category_id_seq')), current_date, current_date, 'Business', null, 'business');
insert into category values ((select nextval('category_id_seq')), current_date, current_date, 'Health & Fitness', null, 'health-&-fitness');
insert into category values ((select nextval('category_id_seq')), current_date, current_date, 'Comedy', null, 'comedy');

insert into podcast values ((select nextval('podcast_id_seq')), current_date, current_date, 'The Daily', '0', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjZt805JMihjChbsRmtabBwt86kFvGcdEdzg2Fg-rP_hPUo6We', 'This is what the news should sound like. The biggest stories of our time, told by the best journalists in the world. Hosted by Michael Barbaro. Twenty minutes a day, five days a week, ready by 6 a.m.', (select id from category where name = 'News'), 1);
insert into podcast values ((select nextval('podcast_id_seq')), current_date, current_date, 'SmartLess', '0', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQI50j9o7OQ8j9DPTnqjsTK5po0Fbfh7eHVG1tOIKW2BR713w2E', '"SmartLess" with Jason Bateman, Sean Hayes, & Will Arnett is a podcast that connects and unites people from all walks of life to learn about shared experiences through thoughtful dialogue and organic hilarity. A nice surprise: in each episode of SmartLess, one of the hosts reveals his mystery guest to the other two. What ensues is a genuinely improvised and authentic conversation filled with laughter and newfound knowledge to feed the SmartLess mind. ', (select id from category where name = 'Education'), 1);
insert into podcast values ((select nextval('podcast_id_seq')), current_date, current_date, 'How I Built This with Guy Raz', '0', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQQVGkP2VFTGLtJWzGqsqFb0EBrl30UW4aGRbf-LRm3Het88n0', 'Guy Raz dives into the stories behind some of the world''s best known companies. How I Built This weaves a narrative journey about innovators, entrepreneurs and idealists—and the movements they built. Order the How I Built This book at https://www.guyraz.com/', (select id from category where name = 'Business'), 1);
insert into podcast values ((select nextval('podcast_id_seq')), current_date, current_date, '7 Good Minutes Daily Self-Improvement Podcast', '0', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoT9wuGi5f8aUnktGKqPbGdpoft9Bp64Z03Mp51UHkFLfK4Ubn', 'Start Each Day The Right Way With The 7 Good Minutes Daily Self-Improvement Podcast. The Podcast for Busy High Achievers, Hosted by Clyde Lee Dennis. Where you get self-improvement tips, life skills training, and the inspiration you need as you work toward achieving your goals. With a new 7 minute episode every day 7 days a week featuring the best teachers and speakers like Brendon Burchard, Joel Osteen, Mel Robbins, Simon Sinek, Eddie Pinero, Lisa Nichols, Robin Sharma, Jay Shetty, and many more. Subscribe now so you never miss a new episode!', (select id from category where name = 'Health & Fitness'), 1);
insert into podcast values ((select nextval('podcast_id_seq')), current_date, current_date, 'Conan O''Brien Needs A Friend', '0', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSfHG4Hb0Cbz4cZSb_syTrBqwXltb3i-La779QE549yMC81vI', 'After 25 years at the Late Night desk, Conan realized that the only people at his holiday party are the men and women who work for him. Over the years and despite thousands of interviews, Conan has never made a real and lasting friendship with any of his celebrity guests. So, he started a podcast to do just that. Deeper, unboundedly playful, and free from FCC regulations, Conan O’Brien Needs a Friend is a weekly opportunity for Conan to hang out with the people he enjoys most and perhaps find some real friendship along the way.', (select id from category where name = 'Comedy'), 1);

insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'The Sunday Read: ''Rembrandt in the Blood''', 'It was in the winter of 2016 that Jan Six, a Dutch art dealer based in Amsterdam, made a discovery that would upend his life. He was leafing through a Christie’s catalog when he spotted a painting featuring a young man wearing a dazed look, a lace collar and a proto-Led Zeppelin coif. Christie’s had labeled it a painting by one of Rembrandt’s followers, but Mr. Six knew it was by the Dutch master himself. Today on The Sunday Read, a look at Mr. Six’s discovery of the first new Rembrandt painting in over four decades, and the fallout from finding it. _This story was written by Russell Shorto and recorded by Audm. To hear more audio stories from publishers like The New York Times, __download Audm for iPhone or Android__._', (select id from podcast where title = 'The Daily'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'A Nursing Home’s First Day Out of Lockdown', 'The Good Shepherd Nursing Home in West Virginia lifted its coronavirus lockdown in February. For months, residents had been confined to their rooms, unable to mix. But with everybody now vaccinated, it was finally time to see one another again. We share some of the relief and joy about the tip-toe back to normalcy for staff members and residents. Guest: Sarah Mervosh, a national reporter for The New York Times. Sign up here to get The Daily in your inbox each morning. And for an exclusive look at how the biggest stories on our show come together, subscribe to our newsletter. Background reading: * The Good Shepherd Nursing Home, where vaccinations have finished, offers a glimpse at what the other side of the pandemic might look like. * Nursing homes, once hot spots of the coronavirus, are far outpacing the rest of the United States in Covid declines. For more information on today’s episode, visit nytimes.com/thedaily. Transcripts of each episode will be made available by the next workday.', (select id from podcast where title = 'The Daily'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'The State of Vaccinations', 'The United States has never undertaken a vaccination campaign of the scale and speed of the Covid-19 program. Despite a few glitches, the country appears to be on track to offer shots to all adults who want one by May 1. We look at the ups and downs in the American vaccination campaign and describe what life after inoculation might look like. Guest: Apoorva Mandavilli, a science and global health reporter for The New York Times. Sign up here to get The Daily in your inbox each morning. And for an exclusive look at how the biggest stories on our show come together, subscribe to our newsletter. Background reading: * It’s not clear how easily vaccinated people may spread the virus, but the answer to that question is coming soon. Until then, scientists urge caution. * Many scientists are expecting another rise in infections. But this time, vaccinations should help to counter the surge. By summer, Americans may be looking at a return to normal life. For more information on today’s episode, visit nytimes.com/thedaily. Transcripts of each episode will be made available by the next workday.', (select id from podcast where title = 'The Daily'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Stephen Colbert', 'This week we take a wild ride through the brain of Mr. Stephen Colbert (host, comedian, pro skier). The gang examines Jason''s ''pleasant hostility,'' Stephen''s Lord of the Rings memorabilia, and a few ''100% true'' stories.', (select id from podcast where title = 'SmartLess'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'W. Kamau Bell', 'We are joined this week by Mr. W. Kamau Bell, television host and stand-up comic, and wicked smart dude. He tells us about the birds and the bees, when to teach your children new things, and his grand ideas for Ozark''s next season.', (select id from podcast where title = 'SmartLess'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Brad Paisley', 'The incredibly talented Brad Paisley shares his perfect blend of country and comedy while we all blush with a crush. "I''m takin'' my baby out into this cornfield tonight"... is exactly how we felt after the interview too.', (select id from podcast where title = 'SmartLess'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Seth Meyers', 'Comedian and television host Seth Meyers feels anxious and excited about being Conan O’Brien’s friend.  Seth sits down with Conan to talk about coming on to SNL as a cast member first and a writer second, parsing praise from the enigmatic Lorne Michaels, and lessons learned at the Late Night desk. Later, Conan takes it up a notch in his quest for the perfect pen.  Got a question for Conan? Call our voicemail: (323) 451-2821.  For Conan videos, tour dates and more visit TeamCoco.com', (select id from podcast where title = 'Conan O''Brien Needs A Friend'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Kate Hudson', 'Actress and entrepreneur Kate Hudson feels insecure about being Conan O’Brien’s friend. Kate sits down with Conan to talk about the key to being a good salesperson, rediscovering the music of the 90s through her kids, and family lessons learned from iconic parents Goldie Hawn and Kurt Russell. Plus, Conan shares an urgent news update with his team. Got a question for Conan? Call our voicemail: (323) 451-2821. For Conan videos, tour dates and more visit TeamCoco.com.', (select id from podcast where title = 'Conan O''Brien Needs A Friend'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Shaquille O''Neal', 'Basketball legend Shaquille O’Neal feels enigmatic about being Conan O’Brien’s friend. Shaq sits down with Conan to talk about his uniquely philosophical outlook, being yelled at by Charles Barkley’s mother, how he decides which brands to rep, and remembering Kobe. Later, Conan reprimands his assistant Sona over a mistaken order of pens. Got a question for Conan? Call our voicemail: (323) 451-2821. For Conan videos, tour dates and more visit TeamCoco.com.', (select id from podcast where title = 'Conan O''Brien Needs A Friend'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Achieve Your Goals By Never Giving Up On Your Dreams', 'In this episode, we have an inspiring message about Never Giving Up On Your Dreams. Go to https://7goodminutes.com/1179 for full show notes. Don''t forget to subscribe, rate, and share it with a friend or two!', (select id from podcast where title = '7 Good Minutes Daily Self-Improvement Podcast'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Do The Hard Things First', 'In this episode, we learn why it''s important that you Do The Hard Things First. Go to https://7goodminutes.com/1178 for full show notes. Don''t forget to subscribe, rate, and share it with a friend or two!', (select id from podcast where title = '7 Good Minutes Daily Self-Improvement Podcast'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'How To Develop Mental Toughness', 'In this episode, in our Freddy Fri Day segment, we learn How To Develop Mental Toughness. Go to https://7goodminutes.com/1177 for full show notes. Don''t forget to subscribe, rate, and share it with a friend or two!', (select id from podcast where title = '7 Good Minutes Daily Self-Improvement Podcast'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'UPPAbaby: Bob and Lauren Monahan', 'As a product developer, Bob Monahan worked with some iconic brands: the Pump at Reebok, the Taurus and Mustang at Ford. When he moved on to work at a baby products company, he happened to discover another set of wheels that caught his eye: a sleek-looking stroller that could accommodate a car-seat or a bassinet. Bob was itching to start his own venture, so in 2006, with the help of his wife Lauren, he launched UPPAbaby and started selling a European-style stroller at an ''entry-level luxury'' price. As a dad himself, Bob guessed that other dads would be intrigued by UPPAbaby''s design; meanwhile, big-name celebrities started to use the stroller, and photos of them pushing it helped accelerate sales. The brand grew quickly, and 15 years after its launch, UPPAbaby employs over 100 people and sells strollers in more than 50 countries. How I Built This Summit - information and tickets at: http://summit.npr.org', (select id from podcast where title = 'How I Built This with Guy Raz'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'How I Built Resilience: Vivian Ku, Restaurateur', 'Vivian Ku is a Taiwanese-American restaurateur who owns three different Taiwanese restaurants in Los Angeles. After the pandemic halted her plans for expansion, Vivian decided to close her two restaurants until May and pivoted her expansion plans into a breakfast pop-up. Vivian talks to Guy about why she decided to serve Taiwanese food and the pros and cons of opening a restaurant during a pandemic. These conversations are excerpts from our How I Built Resilience series, where Guy talks online with founders and entrepreneurs about how they''re navigating turbulent times.', (select id from podcast where title = 'How I Built This with Guy Raz'),  'audioURL');
insert into episode values ((select nextval('episode_id_seq')), current_date, current_date, 'Hinge: Justin McLeod', 'In 2010, Justin McLeod was in business school, still trying to get over a bad breakup that had happened years before. Determined to solve his own problem and convinced that the best way to meet people was through friends of friends, he built an app to replicate that experience. Gradually, Hinge grew into a streamlined swiping platform that yielded mixed results: good dates, bad hookups, mismatched swipes, and missed opportunities. Disappointed with this outcome and inspired by a sudden twist in his own love life, Justin redesigned Hinge as an app for finding meaningful relationships, with the tag line ''designed to be deleted.'' Today, Hinge is owned by Match Group and is one of the most popular dating apps in the U.S. How I Built This Summit - information and tickets at: http://summit.npr.org', (select id from podcast where title = 'How I Built This with Guy Raz'),  'audioURL');